# 6-DoF Arm
version: 1.0
families: ["Arm"]
names: ["J1_base", "J2_shoulder", "J3_elbow", "J4_wrist1", "J5_wrist2", "J6_wrist3"]
hrdf: "../hrdf/A-2085-06.hrdf"

gains:
  default: "../gains/A-2085-06.xml"

plugins:

  - type: GravityCompensationEffort
    name: gravComp
    enabled: true
    ramp_time: 0

  - type: DynamicsCompensationEffort
    name: dynamicsComp
    enabled: true
    ramp_time: 0

user_data:

  # Three waypoints for Buttons - B1, B2, B3
  waypoints:
  - [0, 0, 0, 0, 0, 0]
  - [0.7853981633974483, 1.0471975511965976, 2.0943951023931953, 1.0471975511965976, 0.7853981633974483, 0] # [pi/4, pi/3, 2*pi/3, pi/3, pi/4, 0]
  - [-0.7853981633974483, 1.0471975511965976, 2.0943951023931953, 1.0471975511965976, 2.356194490192345, 0] # [-pi/4, pi/3, 2*pi/3, pi/3, 3*pi/4, 0]

  # Time taken to travel to a waypoint
  travel_time: 3 # seconds

  mobile_io:
    family: "Arm"
    layout: "../layouts/ex_mobile_io_control.json"
    name: "mobileIO"